export const firstName = 'Nikola'
export const lastName = 'Nikolic'
export const password = '12345678'
export const validEmail = 'dragan1@gmail.com'
export const validPassword = '12345678'
export const shortPass = '1234567'
export const passNoDigits = 'qasdfvbt'
export const invalidEmail = 'dragan1@gmailcom'
export const invalidEmail2 = 'dragan1gmail.com'
export const space = ' '
//'{backspace}'
export const title = 'nature'